server.port: 8080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    non-secure-port: ${PORT:8989}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gateway
  redis:
    host: localhost
    password:
    port: 6379
  cloud:
    gateway:
#如果你想关闭gateway，可以使用配置spring.cloud.gateway.enabled=false
      enabled: true
#是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      discovery:
        locator:
          enabled: true
      routes:
      - id: ok                     #网关路由到网易官网
        uri: http://www.163.com/
        predicates:
          - Path=/163/**
      - id: v360
        uri: http://www.360.cn
        predicates:
        - Path=/consumingserviceendpoint
        filters:
        - StripPrefix=2

        



#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG